export const FETCH_GIPHY_SUCCESS = 'FETCH_GIPHY_SUCCESS';
export const WAIT_GIPHY = 'WAIT_GIPHY';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FIND_BLOG_SUCCESS = 'FIND_BLOG_SUCCESS';