export const FETCH_GIPHY_SUCCESS = 'FETCH_GIPHY_SUCCESS';
export const WAIT_GIPHY = 'WAIT_GIPHY';
export const WAIT_POST = 'WAIT_POST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FIND_POST_SUCCESS = 'FIND_POST_SUCCESS';
